# you may not use this file except in compliance with the License.More actions
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
Common:
  model: Qwen/Qwen3-0.6B

  block-size: 16
  max-model-len: 16384
  served_model_name: Qwen/Qwen3-0.6B

Frontend:
  port: 8000
  router_mode: kv

VllmDecodeWorker:
  enforce-eager: true
  max-num-batched-tokens: 16384
  enable-prefix-caching: true
  data-parallel-address: 127.0.0.1
  data-parallel-rpc-port: 62300
  data-parallel-size: 2
  data-parallel-size-local: 1
  # api-server-count: 2

  ServiceArgs:
    workers: 1  # 2 workers
    resources:
      gpu: 1  # 2 dp ranks
  common-configs: [model, served_model_name, block-size, max-model-len]
